version: "3"
services:
  mysql:
    image: "mysql:8"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "yes"
      MYSQL_USER: "friend"
      MYSQL_PASSWORD: "ChangeMe"
      MYSQL_DATABASE: 'dm_friend'
    volumes:
      - ./mysql-data/:/var/lib/mysql/
